# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.2
FROM node:lts-alpine AS builder
WORKDIR /app
RUN apk add --no-cache python3 g++ make
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/index.js"]
